### PR TITLE
Pre-empted driver quitting with a .close

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
See https://github.com/mozilla/geckodriver/issues/1151. It looks like at least Firefox will annoyingly remain open if a page has certain kinds of modal dialogs.
Although it's a teeny bit messy, I don't think it can hurt to _really_ close the browser.

### CODE REVIEW

**Comment by alexeyraspopov** [comment]
I hope this also fixes an issue with Safari that I've observed a while ago. Let me check the changes locally, before merging this in.

Thanks for doing this!

**Comment by JoshuaKGoldberg** [comment]
Ping @alexeyraspopov - any update? 😊

**Comment by JoshuaKGoldberg** [comment]
Added another fix here: sometimes, if there's an error in setup, `this.driver` is `undefined`. That causes `teardown` to fail on the `.close()`. 

Solution: check `if (this.driver)`.

**Comment by JoshuaKGoldberg** [comment]
....and this opens #8. 😂

Edited PR to address it preemptively.

**Comment by alexeyraspopov** [comment]
Sorry for this huge delay. I didn't have enough time to continue this project. I'm really sorry.

**Pull request merged**
